### ISSUE TITLE
Wrong path for `storj-up localbin -s s:\xyz satellite-api`

### ISSUE THREAD

**Issue by egonelbre** [storj/up#23]
Running locally:

```
storj-up local-bin -s "s:\core\storj\cmd\satellite" satellite-core satellite-admin satellite-api
```

Ended up creating a compose file:

```
    volumes:
    - type: bind
      source: "F:\\Go/bin/s:\\core\\storj\\cmd\\satellite/satellite"
      target: /var/lib/storj/go/bin/satellite
      bind:
        create_host_path: true
```

Similarly, if there already exists such a volume mount, it adds a new one rather than replacing the existing one.
