### ISSUE TITLE
Storj-up add auditor and repair

### ISSUE THREAD

**Issue by littleskunk** [storj/up#80]
I had to manually modify my docker compose file to get audit and repair working. It would be great to just call `storj-up add repair` in the future.

This was my config at the end. I didn't care too much about the values so maybe better double check them / change them.
```
  satellite-auditor:
    command:
    - satellite
    - run
    - auditor
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/satellite-api/
    environment:
      STORJUP_SATELLITE: satellite-api
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DATABASE_OPTIONS_MIGRATION_UNSAFE: full
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/satellite-api/
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=1
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <storj-up@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_MAIL_TEMPLATE_PATH: /var/lib/storj/storj/web/satellite/static/emails/
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_OVERLAY_SEND_NODE_EMAILS: "true"
      STORJ_ROLE: satellite-auditor
      STORJ_USE_PREDEFINED_IDENTITY: "1"
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: storj
    networks:
      default: null
  satellite-repair:
    command:
    - satellite
    - run
    - repair
    - --defaults=dev
    - --identity-dir=/var/lib/storj/.local/share/storj/identity/satellite-api/
    environment:
      STORJUP_SATELLITE: satellite-api
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DATABASE_OPTIONS_MIGRATION_UNSAFE: full
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/satellite-api/
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=1
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <storj-up@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_MAIL_TEMPLATE_PATH: /var/lib/storj/storj/web/satellite/static/emails/
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_OVERLAY_SEND_NODE_EMAILS: "true"
      STORJ_ROLE: satellite-repair
      STORJ_USE_PREDEFINED_IDENTITY: "1"
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: storj
    networks:
      default: null
```
