### ISSUE TITLE
Invalid port versioncontrol service

### ISSUE THREAD

**Issue by ifraixedes** [storj/up#98]
## Reason / Why?

storj-up v1.2.7 assigns an invalid port to the versioncontrol service.

When `storj-up init versioncontrol` or any other recipe that adds the versioncontrol service to the `docker-compose.yaml` file is executed it produces the following 

```yaml
version: "3.4"
services:
  versioncontrol:
    command:
    - versioncontrol
    - run
    deploy:
      replicas: 1
    environment:
      BINARY_GATEWAY_ROLLOUT_SEED: "0000000000000000000000000000000000000000000000000000000000000001"
      BINARY_IDENTITY_ROLLOUT_SEED: "0000000000000000000000000000000000000000000000000000000000000001"
      BINARY_SATELLITE_ROLLOUT_SEED: "0000000000000000000000000000000000000000000000000000000000000001"
      BINARY_STORAGENODE_ROLLOUT_SEED: "0000000000000000000000000000000000000000000000000000000000000001"
      BINARY_STORAGENODE_UPDATER_ROLLOUT_SEED: "0000000000000000000000000000000000000000000000000000000000000001"
      BINARY_UPLINK_ROLLOUT_SEED: "0000000000000000000000000000000000000000000000000000000000000001"
      STORJ_ADDRESS: 0.0.0.0:-1
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
    image: img.dev.storj.io/storjup/storj:1.104.5
networks: {}
```

The environment variable `STORJ_ADDRESS: 0.0.0.0:-1` has the -1 port, an invalid port.

## What needs to be done?

Fix the versioncontrol service docker-compose generation to assign a valid port.

## Acceptance criteria

- Fix `storj-up init` with any recipe that adds the versioncontrol service into the `docker-compose.yaml` file to assign a valid port to the `STORJ_ADDRESS` environment variable.
